version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    depends_on:
      - redis

volumes:
  redis_data:
  data:
